### ISSUE TITLE
It does not deploy sns-mobile, aws-sms-send

### ISSUE THREAD

**Issue by ashish-ajm** [dougmoscrop/serverless-plugin-include-dependencies#26]
I require packages sns-mobile, aws-sms-send in my code but it does not deploy these. Can anyone tell me the reason of this issue and how to resolve this.

**Comment by 3boysdad** [comment]
both seems like standard modules that would already be present.  have you had a problem with the code once deployed?

**Comment by ashish-ajm** [comment]
> both seems like standard modules that would already be present. have you had a problem with the code once deployed?

Sir I deploy code and successfully done.. but when i invoke lambda it giving me error that 'node_module not found'

**Comment by 3boysdad** [comment]
can you share your yml file?  i'm not an expert...but i think it would help the developer to take a look as well.

**Comment by ashish-ajm** [comment]
```
functions:  
 XXXXXXXXXXXXX:
    handler: index.handler     
plugins:
  - serverless-export-env
  - serverless-plugin-include-dependencies
package:
  exclude:    
    - .env
```
this is code in .yml and i install package that i mentioned in code
