### ISSUE TITLE
node_modules is empty

### ISSUE THREAD

**Issue by dineshrawat11** [dougmoscrop/serverless-plugin-include-dependencies#54]
This is my yml file:
```
service: covation-labs-api
provider:
  name: aws
  runtime: nodejs10.x
  stage: v1
  region: eu-central-1
  memorySize: 128
package:
  excludeDevDependencies: false
  individually: true
  include:
    - dist/**
    - package.json
plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
custom:
  includeDependencies:
    always:
      - 'dist/**' 
functions:
  app:
    handler: dist/lambda.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
```
The problem is the node modules are not moving inside node_modules. I want have all the packages in node_modules which are used inside /dist folder. Please help!
