### ISSUE TITLE
Manually including packages

### ISSUE THREAD

**Issue by alexcroox** [dougmoscrop/serverless-plugin-include-dependencies#57]
Is it possible to manually include deps? I have a Nuxt app which defines these in nuxt.config.js so I doubt this plugin could auto pick them up, which is fine I don't mind adding them manually, but I can't work out where and attempts have failed:

```
custom:
  includeDependencies:
    always:
      - 'api/**'
      - 'node_modules/nuxt-i18n' <-- this one
     
functions:
  render:
    handler: server/edge.handler
    memorySize: 512
    timeout: 10
    lambdaAtEdge:
      distribution: 'NuxtEdgeDistribution'
      eventType: 'origin-request'
    package:
      excludeDevDependencies: true
      exclude:
        - 'assets/**'
        - 'components/**'
        - 'layouts/**'
        - 'components/**'
        - 'middleware/**'
        - 'pages/**'
        - 'plugins/**'
        - '.github/**'
        - '.vscode/**'
      include:
        - '.nuxt/**'
        - 'server/edge.js'
        - 'nuxt.config.js'
        - 'node_modules/nuxt-i18n' <-- tried it here too
```
