### ISSUE TITLE
Plug-in ignores package exclude(?)

### ISSUE THREAD

**Issue by neverendingqs** [dougmoscrop/serverless-plugin-include-dependencies#9]
(Related to #6)

I have the following (slight modification from files created with `sls create`):

serverless.yml:
```yaml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs4.3

package:
  exclude:
    - node_modules/aws-sdk/**

plugins:
  - serverless-plugin-include-dependencies

functions:
  hello:
    handler: handler.hello
```

handler.js:

```js
'use strict';

const aws = require('aws-sdk')

module.exports.hello = (event, context, callback) => {
  const response = {
    statusCode: 200,
    body: JSON.stringify({
      message: 'Go Serverless v1.0! Your function executed successfully!',
      input: event,
    }),
  };

  callback(null, response);

  // Use this code if you don't use the http event with the LAMBDA-PROXY integration
  // callback(null, { message: 'Go Serverless v1.0! Your function executed successfully!', event });
};
```

Running `sls deploy --noDeploy` produces a `aws-node.zip` package that includes `node_modules/aws-sdk`.

Removing the `serverless-plugin-include-dependencies` plugin produces a package that does not include `node_modules/aws-sdk`.

Does this plugin ignore entries in package exclude?
